name: flutter_weather
description: Simple weather forecast
publish_to: 'none'
version: 99.99.99

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc: '^6.0.3'
  cupertino_icons: '^1.0.0'
  equatable: '^1.2.5'
  firebase_analytics: '^7.0.0'
  firebase_core: '^0.6.0'
  flutter_bloc: '^6.0.5'
  flutter_form_bloc: '^0.19.0'
  flutter_switch: '^0.2.0'
  http: '^0.12.2'
  hydrated_bloc: '^6.0.1'
  iso_countries: '^1.1.1'
  package_info: '^0.4.3+2'
  page_view_indicators: '^1.4.0'
  select_dialog: '^1.2.1'
  uuid: '^2.2.2'
  weather_icons: '^2.0.2'
  webview_flutter: '^1.0.7'

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: '^1.15.7'
  build_runner: '^1.10.0'
  flutter_launcher_icons: '^0.8.1'
  flutter_native_splash: '^0.2.4'

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_icons:
  adaptive_icon_background: 'assets/images/launcher_background.png'
  adaptive_icon_foreground: 'assets/images/launcher_foreground.png'
  image_path_ios: 'assets/images/launcher.png'
  image_path_android: 'assets/images/launcher.png'
  android: true
  ios: true

flutter_native_splash:
  image: 'assets/images/splash_notext.png'
  color: '#FFFFFF'
  # image_dark: 'assets/images/splash_invert.png'
  image_dark: 'assets/images/splash_notext.png'
  color_dark: '#262626'