# name: "Deploy to Firebase Hosting on merge"

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build_and_deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - 
#         uses: actions/checkout@v1
#       - 
#         run: npm ci
#       - 
#         name: "Nrwl Nx"
#         uses: MansaGroup/nrwl-nx-action@v2.0.3
#         with:
#           targets: build
#           projects: web_ng
#       - 
#         uses: FirebaseExtended/action-hosting-deploy@v0
#         with:
#           repoToken: "${{ secrets.GITHUB_TOKEN }}"
#           firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_MY_FLUTTER_WEATHER }}"
#           channelId: live
#           projectId: "${{ secrets.FIREBASE_PROJECT_ID }}"
#         env:
#           FIREBASE_CLI_PREVIEWS: hostingchannels